// commons package contains commonly used constants and utilities.
package commons

const (
	// ErrorNoData ...
	ErrorNoData = "no data found"
	// ErrorInvalidToken ...
	ErrorInvalidToken = "token is invalid"
	// InValidData ...
	InValidData = "invalid data: %v"
	// ErrorInvalidPassword ...
	ErrorInvalidPassword = "invalid password"
	// ErrorNoRow ...
	ErrorNoRow = "no rows in result set"
	// ErrSystemError ...
	ErrSystemError = "system error"
	// ErrUserExists ...
	ErrUserExists = "phone number already exists"
	// IDClaimKey ...
	IDClaimKey = "id"
	// ExpClaimKey ...
	ExpClaimKey = "exp"
)
